#!/usr/bin/env python

import logging
import sys

from omnisync.main import OmniSync, parse_arguments
from omnisync.configuration import Configuration

# Initialise the logger.
logging.basicConfig(level=logging.INFO, format='%(message)s',
    stream=sys.stdout)

osync = OmniSync()
(options, args) = parse_arguments(osync)
osync.config = Configuration(options)
osync.sync(args[0], args[1])
